version: "3"
services:
  go:
    build:
      context: ./docker/go
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    tty: true
    env_file:
      - .env
  lambda:
    build:
      context: ./docker/lambda
      dockerfile: Dockerfile
    image: go-lambda
    container_name: go-lambda
    ports:
      - "9000:8080"
    volumes:
      - .:/usr/src/app
    tty: true
    env_file:
      - .env
